apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: crak-statefulset-ondelete
spec:
  updateStrategy:
    type: OnDelete
  serviceName: "crak-ondelete"
  replicas: 3
  selector:
    matchLabels:
      app: crak-ondelete
  template:
    metadata:
      labels:
        app: crak-ondelete
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80